### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by df7cb** [dvarrazzo/pgmp#16]
Debian is working on dropping python2, and pgmp is one of the packages on the radar because of the embedded python code. I started looking into what needs to be done, but quickly realized there's a lot of code affected, especially because of the embedded code in `sql/pgmp.pysql`.

Is pgmp still alive? Does it make sense to put in that work? Maybe you could do the porting upstream?

Thanks.

**Comment by dvarrazzo** [comment]
It's probably not much work to port that code to Py3.

Looks like pgmp is still used and there is desire to port it to newer PG versions, so let's say it's not dead just yet.

**Comment by cpaelzer** [comment]
Hi, with the python transition starting the next stage (making python==python3 and python2 being explicit) this comes up again - therefore I wanted to ask if there is anything new on this one?

**Comment by dvarrazzo** [comment]
I am setting up a funding page to support the project, about to launch in these days.

Is there interest to contribute?

**Comment by df7cb** [comment]
Could you maybe merge the outstanding pull requests? Working around this is really costing a lot of packaging time. It's nice if you manage to get funding for pgmp, but if you hold back merging changes because you are waiting for funding, I'd rather remove the package from Debian instead.

**Comment by df7cb** [comment]
IOW, I already contributed #8, #11, and #15 in 2016, 2017, and 2019.

**Comment by dvarrazzo** [comment]
@df7cb thank you for that. I will pull your work together and look at the py3 compatibility.

**Comment by dvarrazzo** [comment]
Fixed in maint-1.0
