### ISSUE TITLE
Classical Mathematics Support

### ISSUE THREAD

**Issue by PowerUser1234** [dvarrazzo/pgmp#22]
-Integer (mpz) Z, or Rational Decimal Q (mpq) numbers support.

-A defaulting number of significat figures, say, 100, or a constructor for otherwise.
 mpz(1000) or mpq(1000), or mpz, mpq just on their own, with no more specified.

-Value assignment by =.  The ability to specify type without any text data in a constructor.

-Base 10 Arithmetic and comparisons support on Base 10 Integer and Rational Decimal numbers.
+,-,*,/,%,=,!=,<>,>,<,>=,<=, ::

-Mathematical and Operational functions support:

cast(text as mpz) returns mpz;
cast(text as mpq) returns mpq;
cast(mpq as text) returns text;
cast(mpz as text) returns text;
cast(mpz as mpq) returns mpq;
cast(mpq as mpz) returns mpz;

sign(mpq input) returns mpq;
abs(mpq input) returns mpq;
ceil(mpq input) returns mpq;
floor(mpq input) returns mpq;
pi(mpz places) returns mpq;
e(mpz places) returns mpq;
power(mpq base, mpq exponent) returns mpq;
sqrt(mpq input) returns mpq
nroot(mpz theroot, mpq input) returns mpq;
log10(mpq input) returns mpq;
loge(mpq input) returns mpq;
log2(mpq input) returns mpq;
factorial(mpz input) returns mpz;

degrees(mpq input) returns mpq;
radians(mpq input) returns ht;
sind(mpq input) returns mpq;
cosd(mpq input) returns mpq;
tand(mpq input) returns mpq;
asind(mpq input) returns mpq;
acosd(mpq input) returns mpq;
atand(mpq input) returns mpq;
sinr(mpq input) returns mpq;
cosr(mpq input) returns mpq;
tanr(mpq input) returns mpq;
asinr(mpq input) returns mpq;
acosr(mpq input) returns mpq;
atanr(mpq input) returns mpq;

-Informative articles on all these things exist at:
Arithmetic Operations: [https://en.wikipedia.org/wiki/Arithmetic](https://en.wikipedia.org/wiki/Arithmetic)
Integer Division: [https://en.wikipedia.org/wiki/Division_(mathematics)#Of_integers](https://en.wikipedia.org/wiki/Division_(mathematics)#Of_integers)
Modulus Operation: [https://en.wikipedia.org/wiki/Modulo_operation](https://en.wikipedia.org/wiki/Modulo_operation)
Factorial Operation: [https://en.wikipedia.org/wiki/Factorial](https://en.wikipedia.org/wiki/Factorial)
Comparison Operators: [https://en.wikipedia.org/wiki/Relational_operator](https://en.wikipedia.org/wiki/Relational_operator)
Degrees: [https://en.wikipedia.org/wiki/Degree_(angle)](https://en.wikipedia.org/wiki/Degree_(angle))
Radians: [https://en.wikipedia.org/wiki/Radian](https://en.wikipedia.org/wiki/Radian)
Elementary Functions: [https://en.wikipedia.org/wiki/Elementary_function](https://en.wikipedia.org/wiki/Elementary_function)

-Another idea, might it be a good idea to turn mpz and mpq into MPZ and MPQ, to line up with the use of other
types in PostgreSQL?

-Ease of installation support.  Particularly for Windows and Linux.  *.exe, *.msi or *.rpm, *.deb, *.bin installers.
With a PostgreSQL standard installation.

**Comment by dvarrazzo** [comment]
What would be `sqrt(2`) as an `mpq`?

**Comment by PowerUser1234** [comment]
Dear DV,

That function name represents the square root of a rational number.  As a Multiprecision Rational,
The first 80 significant figures, to a precision of 80, are:

sqrt(2) -> 1.414213562373095048801688724209698078569671875376948073176679737990732478462107

Admittedly, when an (mpz) or (mpr) is declared, and before it is assigned, you will need to probably use the (text)
type to specify defaulting precision of a number type, before it is assigned to or operated on or by.

________________________________

**Comment by PowerUser1234** [comment]
Dear DV,

In addition to the issues to change I have posted at:

https://github.com/dvarrazzo/pgmp/issues/22

mpz and mpz should have both the ability
to specify precision and the start, or specify
no precision at the start, whereby its non-specify precision
could be, say, 100 significant figures to start, with
room for a larger range, by TEXT type parameter.

?

**Comment by dvarrazzo** [comment]
mpq represent rational numbers, not transcendent numbers or their approximations.

What you have in mind is probably closer to providing approximate floating point numbers and functional such as wrapping the mpfr library. This is not a minor task and will not happen unless the project is sponsored.

**Comment by PowerUser1234** [comment]
Okay.  From here I have two questions.

1)  In terms of what I have specified at the top of this discussion, how much time would it take
     to develop and sufficiently test and debug this extension, with distributed standalone installers?

2) How much sonsership per month should I specify to GitHub sponser?
