### ISSUE TITLE
Extra pgmp Features?

### ISSUE THREAD

**Issue by PowerUser1234** [dvarrazzo/pgmp#23]
Dear Daniele,

my name is Zachary Mitchell and I am from Australia.  I am interested in PostgreSQL,
and your pgmp extension has gathered my attention in a big way.

I was wondering if your two types, mpz and mpq, in this extension, come with extra calculator functions
support or extra type binding support (like range or multirange type support).  If not, I was wondering if
you have the option to build them in to pgmp?

My ideas are in the file attachment. Have a look at it all and see what you think.  Are you able to implement
these additions to pgmp?

At any rate, can you please email reply to me when you have considered all of my submission material.

I look forward to hearing what you think,

Yours Sincerely,

Zachary Mitchell.

Z.M. 

--------------------------------------------------------------------------------------------------------------------------------

I have been trying to find active interest in development of a GPL license style PostgreSQL extension, complete and available, on Sourceforge, PGXN and the public internet, as a volunteer development project, that will support the following:

High Precision Denary Arithmetic and Functions Support      
               In PostgreSQL v14 and beyond.                  
      HPPM: High Precision PostgreSQL Mathematics.            

-I suggest there should be the introduction of Integer Z, or Rational Mixed Decimal Q, numbers support in 64 bit PostgreSQL. Via MPZ, and MPQ, original types. In this specification, they are collectively referred to as HPX types. These two types can be spelled in capital letters, or lower case in PostgreSQL source code. They are:

MPZ, MPQ or mpz, mpq.
MPZ(n), MPQ(n), mpz(n), or mpq(n).

HPX types can be declared like TEXT (with no associated value) or with an associated value, like varchar(n).  IF HPX variables are declared with no associated value, the associated value for that variable is 20.

There should be range and multirange types corresponding to both HPX types: 

MPZRANGE, mpzrange, MPZMULTIRANGE, mpzmultirange. 
MPQRANGE, mpqrange, MPQMULTIRANGE, mpqmultirange.

-The extension could be based on another 3rd party library, and will be written in C. There is already some support for this kind of mathematics, in terms of its logic, and optimisation, publicly available, in C, as Free Open Source Software. That can be researched and apprehended for this extension and for all the relevant PostgreSQL OS platforms that it (HPPM) is designed for by the accepting developers.

-Real numbers are comprised of the values of Integers, non-recurring Rational Numbers and recurring, and/or Irrational Numbers. Recurring and Irrational numbers can be appropriately truncated, ultimately via another positive Integer value, being a count of the desired figures, the precision, always at least 1, to obtain a Rational number.  This value can possibly contain Integer or Decimal parts, or both. These numbers may be positive or negative, or zero, scalar values, and always do exist on the one dimensional number line. 

-HPX 'associated values' will be a number of relevant positive Integer figures (precision), that will get stored with each HPX type variable or column type. These are specified at type or variable declaration, before further use. Or the total defaulting precision amount is applied, being 20, as already stated. 

Precision can be accessed and changed by means of new types being declared, and the old variable being assigned into a new one.  Precision of a type value should be apprehended before calculation begins.  Precision is used to control number operations, and value output, when any numeric manipulation or processing occurs, since things that may go towards an infinity need to be stopped before then, to be useful.

If an HPX value is data on its own, without any set precision, it has the precision amount of the count of its own digits. If it is inserted into a table column with a different precision, then that precision is applied and the data taken in, be it larger or equal. If it less than the new precision, the result result should be no acceptance of the data and an error being thrown.  

If an HPX value, in a PostgreSQL code expression, is sent straight into a RETURN statement or a SELECT statement, without assignment or precision alteration, or is just specified in a comparison expression, then that datum will contain the highest precision value out of any of the others in its expression, by checking the largest one found as the expression is considered, from left to right, within its sub expression.  This holds for data or type variables.

If such a precision value cannot be arrived at, because the value is irrational or infinitely reccuring, then the default precision value for truncation will be 20, and truncation will occur.

-This whole system will uphold precision for very many denary numbers, certainly ones within a very large range limit, controlled by the already available type for large positive integers, the BIGINT. It can thereby enumerate digits within the range of 
(+/-)1 to (+/-)9,223,372,036,854,775,807. This is at least between one and positive nine quintilion digit places.  More than enough for the speed and scope of today, or maybe tomorrow, and the Desktop PC, as either a client or a server.

Naturally, evaluation will slow down, or not conclude in useful time frames, before those limits, presently, as more mathematics is done to make numbers ever larger or ever smaller (maybe both).  These phenomenon can be allowed, and left to the programmer to deal with or curtail. 

A TEXT variable or table column, or even another HPX or numeric type (if the data of the value is in range) can be used to store digit data alone. Mixed Decimals can be broken down into integers and dealt with from there using operators, and reassembled into mixed integers again, if absolutely necessary, although this will be slower and inneficient internally.

--At the point of PostgreSQL code input and execution:

select pi(1001) as pi;

--HPX types can be declared like TEXT or
--like varchar(n),
--Within a table creation command:

create table example_table
(
id BIGSERIAL PRIMARY KEY,
a MPZ,
b MPQ(50)
);

ALTER TABLE example_table ALTER COLUMN b TYPE MPQ(30);
ALTER TABLE example_table ALTER COLUMN b TYPE MPQ(30);

INSERT INTO example_table(a,b) VALUES(0,  0.1);
INSERT INTO example_table(a,b) VALUES(100,1.1);
INSERT INTO example_table(a,b) VALUES(200,2.2);
INSERT INTO example_table(a,b) VALUES(300,3.3);
INSERT INTO example_table(a,b) VALUES(400,4.4);
INSERT INTO example_table(a,b) VALUES(500,5.5);
INSERT INTO example_table(a,b) VALUES(600,6.6);
INSERT INTO example_table(a,b) VALUES(700,7.7);
INSERT INTO example_table(a,b) VALUES(800,8.8);
INSERT INTO example_table(a,b) VALUES(900,9.9);

--Or as variables, in some function:

create or replace function example_function()
returns void
language plpgsql
as
$$
declare
a MPQ; 
b MPQ(2);
c MPQ(3);
begin
a = 0.1;
b = 0.1;
c=a*b;
return void
end;
$$

--Range and Multirange Types or Functions or Operators.

select mpzrange(1,3) && mpzrange(3,20)  AS Intersecting;

select mpqrange(1.5,3) mpqrange(3,25.5) AS Mixed_Number_Range;

-Value assignment to a typed variable by =.

-Operators.  Base 10 Arithmetic and comparisons support on Base 10 MPZ and MPQ, with casting:

::,=,!=,<>,>,<,>=,<=,+,-,*,/,%,^

These include full division and integer only division (from type inference, between two MPZ integers, only), with no remainder, and a remainder only calculating operator (for all type circumstances), within all range possibilities of the involved two values under a particular operation. The also include a power or exponentiation operator.

##############################################################
There should be a property of value inversion equality.
Consider the following source code fragment as an example:

a = 1;      
b = 7;       
c = a/b;       
output(c);       
d = c*b;       
output(d);
output(d == a); //true
##############################################################
-REIFIED SUPPORT with broader syntax and operations and phenomena within PostgreSQL.  Range and Multirange types, HPX integration with Tables, the between keyword, Array types, Indexing, Variables and related phenomena, the Record type, direct compatibility with the Aggregate and Window functions, and Partitions are all parts of a larger subset that should re-interact with MPZ or MPQ successfully.  HPX types should also be integrated with Range Types, Multirange Types, Operators, their Functions and their Window Functions.  
##############################################################

-Ease of installation support. Particularly for Windows and Linux. *.exe, *.msi or *.rpm, *.deb, *.bin, *.sh installer prefixes for a PostgreSQL installation from one file, each.  Installation, Activation and Use instructions should be included, necessary for successful use, and the uninitiated. The extension should literally just install and be applicable, with no loading command necessary (if possible). For every time the PostgreSQL database process is run, by default. 

-Mathematical and Operational functions support:

cast(MPZ as MPQ)  returns MPQ;
cast(MPQ as MPZ)  returns MPZ;
cast(TEXT as MPZ) returns MPZ;
cast(TEXT as MPQ) returns MPQ;
cast(MPQ as TEXT) returns TEXT;
cast(MPZ as TEXT) returns TEXT;
cast(MPZ as SMALLINT) returns SMALLINT;
cast(SMALLINT as MPZ) returns MPZ;
cast(MPZ as INTEGER)  returns INTEGER;
cast(INTEGER as MPZ)  returns MPZ;
cast(MPZ as BIGINT)   returns BIGINT;
cast(BIGINT as MPZ)   returns MPZ;
cast(MPQ as REAL)     returns REAL;
cast(REAL as MPQ)     returns MPQ;
cast(DOUBLE PRECISION as MPQ) returns MPQ;
cast(MPQ as DOUBLE PRECISION) returns DOUBLE PRECISION;
cast(MPQ as DECIMAL)  returns DECIMAL;
cast(DECIMAL as MPQ)  returns MPQ;
cast(MPQ as NUMERIC)  returns NUMERIC;
cast(NUMERIC as MPQ)  returns MPQ;

sign(MPQ input)  returns MPZ;
abs(MPQ input)   returns MPZ;
ceil(MPQ input)  returns MPZ;
floor(MPQ input) returns MPZ;
round(MPQ input) returns MPZ;
factorial(MPZ input) returns MPZ;
nCr(MPZ objects, MPZ selectionSize) returns MPZ;
nPr(MPZ objects, MPZ selectionSize) returns MPZ;

reciprocal(MPQ input) returns MPQ;
pi(BIGINT precision)  returns MPQ;
e(BIGINT precision)   returns MPQ;
power(MPQ base, MPQ exponent) returns MPQ;
sqrt(MPQ input) returns MPQ;
nroot(MPZ theroot, MPQ input) returns MPQ;
log10(MPQ input) returns MPQ;
ln(MPQ input)    returns MPQ;
log2(MPQ input)  returns MPQ;

radtodeg(MPQ input)returns MPQ;
degtorad(MPQ input)returns MPQ;
sind(MPQ input)    returns MPQ;
cosd(MPQ input)    returns MPQ;
tand(MPQ input)    returns MPQ;
asind(MPQ input)   returns MPQ;
acosd(MPQ input)   returns MPQ;
atand(MPQ input)   returns MPQ;
sinr(MPQ input)    returns MPQ;
cosr(MPQ input)    returns MPQ;
tanr(MPQ input)    returns MPQ;
asinr(MPQ input)   returns MPQ;
acosr(MPQ input)   returns MPQ;
atanr(MPQ input)   returns MPQ;

-Informative articles on all these things exist at:

PostgreSQL v14 Database Documentation:
https://www.postgresql.org/docs/14/index.html
Comparison Operators: https://en.wikipedia.org/wiki/Relational_operator
Floor and Ceiling Functions: https://en.wikipedia.org/wiki/Floor_and_ceiling_functions
Arithmetic Operations: https://en.wikipedia.org/wiki/Arithmetic
Integer Division: https://en.wikipedia.org/wiki/Division_(mathematics)#Of_integers
Modulus Operation: https://en.wikipedia.org/wiki/Modulo_operation
Rounding (Commercial Rounding): https://en.wikipedia.org/wiki/Rounding
Factorial Operation: https://en.wikipedia.org/wiki/Factorial
Degrees: https://en.wikipedia.org/wiki/Degree_(angle)
Radians: https://en.wikipedia.org/wiki/Radian
Elementary Functions: https://en.wikipedia.org/wiki/Elementary_function
Trigonometry key values and the Unit Circle:
https://courses.lumenlearning.com/boundless-algebra/chapter/trigonometric-functions-and-the-unit-circle/

                           The End.

--------------------------------------------------------------------------------------------------------------------------------

**Comment by dvarrazzo** [comment]
You can use `CREATE RANGE` to create a range on MPZ or MPQ.

For the rest, [we already had this conversation](https://groups.google.com/g/pgxn-users/c/cm6CEQKPWRU/m/UtOvWbhfAgAJ?utm_medium=email&utm_source=footer).

I really don't understand what you are looking for. I ask you kindly to not waste our time.
