### ISSUE TITLE
Questions about MPZ, MPQ accompanying functions.

### ISSUE THREAD

**Issue by PowerUser1234** [dvarrazzo/pgmp#24]
I can't find that your MPQ, MPZ types have calculator functions in the PostgreSQL extension
you have published online, with function signatures that look like this:

-------------------------------------------------------------------------------------
sign(MPQ input)  returns MPZ;
abs(MPQ input)   returns MPZ;
ceil(MPQ input)  returns MPZ;
floor(MPQ input) returns MPZ;
round(MPQ input) returns MPZ;
factorial(MPZ input) returns MPZ;
nCr(MPZ objects, MPZ selectionSize) returns MPZ;
nPr(MPZ objects, MPZ selectionSize) returns MPZ;

reciprocal(MPQ input) returns MPQ;
pi(BIGINT precision)  returns MPQ;
e(BIGINT precision)   returns MPQ;
power(MPQ base, MPQ exponent) returns MPQ;
sqrt(MPQ input) returns MPQ;
nroot(MPZ theroot, MPQ input) returns MPQ;
log10(MPQ input) returns MPQ;
ln(MPQ input)    returns MPQ;
log2(MPQ input)  returns MPQ;

radtodeg(MPQ input)returns MPQ;
degtorad(MPQ input)returns MPQ;
sind(MPQ input)    returns MPQ;
cosd(MPQ input)    returns MPQ;
tand(MPQ input)    returns MPQ;
asind(MPQ input)   returns MPQ;
acosd(MPQ input)   returns MPQ;
atand(MPQ input)   returns MPQ;
sinr(MPQ input)    returns MPQ;
cosr(MPQ input)    returns MPQ;
tanr(MPQ input)    returns MPQ;
asinr(MPQ input)   returns MPQ;
acosr(MPQ input)   returns MPQ;
atanr(MPQ input)   returns MPQ;
-------------------------------------------------------------------------------------

Are these sorts of functions included? If so, where is the documentation
for them? If not, are you able to consider putting functions like this in
your PGMP extension?

**Comment by dvarrazzo** [comment]
I will consider including these function only as a sponsored project.
