### ISSUE TITLE
PGMP Sponsored project?

### ISSUE THREAD

**Issue by PowerUser1234** [dvarrazzo/pgmp#25]
-As a sponsored project, about how much money would you consider to 
be enough? 

-What is your local currency? 

-Would a paypal money order email sent to me for payment be an adequete option for you?

-----------------------------------------------------------
sign(MPQ input) returns MPZ;
abs(MPQ input) returns MPZ;
ceil(MPQ input) returns MPZ;
floor(MPQ input) returns MPZ;
round(MPQ input) returns MPZ;
factorial(MPZ input) returns MPZ;
nCr(MPZ objects, MPZ selectionSize) returns MPZ;
nPr(MPZ objects, MPZ selectionSize) returns MPZ;

reciprocal(MPQ input) returns MPQ;
pi(BIGINT precision) returns MPQ;
e(BIGINT precision) returns MPQ;
power(MPQ base, MPQ exponent) returns MPQ;
sqrt(MPQ input) returns MPQ;
nroot(MPZ theroot, MPQ input) returns MPQ;
log10(MPQ input) returns MPQ;
ln(MPQ input) returns MPQ;
log2(MPQ input) returns MPQ;
radtodeg(MPQ input)returns MPQ;
degtorad(MPQ input)returns MPQ;
sind(MPQ input) returns MPQ;
cosd(MPQ input) returns MPQ;
tand(MPQ input) returns MPQ;
asind(MPQ input) returns MPQ;
acosd(MPQ input) returns MPQ;
atand(MPQ input) returns MPQ;
sinr(MPQ input) returns MPQ;
cosr(MPQ input) returns MPQ;
tanr(MPQ input) returns MPQ;
asinr(MPQ input) returns MPQ;
acosr(MPQ input) returns MPQ;
atanr(MPQ input) returns MPQ;
-----------------------------------------------------------

**Comment by dvarrazzo** [comment]
Man,

these are transcendental functions: how can you represent sin(x) as a fraction?

This doesn't make sense at all. Thank you for wanting to throw money at me but this work would be just a waste of time.

**Comment by PowerUser1234** [comment]
Dear Daniele,

I thought that mpq was a mixed number, integer/decimal value,
and not just a fraction of two integers.

At any rate, sin(x) could be represented as a series of fractions,
and in the end, one value.

-Aren't mpz and mpq individual values?

-If they are not, what exactly is an mpq, in expression terms?

-Can't an mpq be a series of sub-mpqs?

Yours Sincerely,

Sergio Minervini.

S.M.

________________________________
