### ISSUE TITLE
PostgreSQL 16 support

### ISSUE THREAD

**Issue by devrimgunduz** [dvarrazzo/pgmp#28]
Hi @dvarrazzo ,

Latest release of pgmp does not compile against PostgreSQL 16, and v16 is due next week. Can you please take a look?

Thanks!

Devrim

**Comment by dvarrazzo** [comment]
Hi Devrim,

that's probably addressed by MR #27: I'll merge it and test in the next days.

**Comment by dvarrazzo** [comment]
pgmp 1.0.5 released with PostgreSQL 16 support.

**Comment by devrimgunduz** [comment]
Thank you!
