### ISSUE TITLE
Result differs from documentation for limit_den using latest versions

### ISSUE THREAD

**Issue by marcelgsteiger** [dvarrazzo/pgmp#36]
I'm successfully using your pgmp extension heavily for years now, all works flawlessly, thanks a lot for your work.

Today I came across a minor issue: In your documentation https://www.varrazzo.com/pgmp/mpq.html you give as an example for limit_den:
```
=# select limit_den(10.1::float4);
101/10
```
but, using current versions of gmp on postgresql 11/Debian buster or postgresql 16 on Arch Linux  (both arm64 on raspberry pi), I get
```
=# select limit_den(10.1::float4);
5295309/524288
```
I either have to use float8 instead of float4 or give a smaller second parameter (e.g. 100000) to get the desired result.

Not much of a problem, perhaps only a documentation issue.

Best regards
Marcel

**Comment by dvarrazzo** [comment]
Probably it's a matter of rounding happening upfront in `10.1::float4`. `float8` or `decimal` don't have the same problem.

I will fix the docs, thank you for the report.
