### ISSUE TITLE
pgfoundry home page no longer there

### ISSUE THREAD

**Issue by petere** [dvarrazzo/pgmp#7]
The home page on pgfoundry is no longer there.  It just says "It works!".

**Comment by dvarrazzo** [comment]
It's long been out of my control: I've not been able to log in on pgfoundry for more than one year. The pkey is not used and my community password doesn't allow ssh login on pgfoundry. I've asked for help on pgfoundry and never received. Of course there's no point in logging in now: it seems the entire pgfoundry is down.

I can move the docs to a github page, which would be more reliable, and change the docs to point there. In the meantime docs are available on [pgxn](http://pgxn.org/dist/pgmp/)

It would be nice if after the project page is up the previous url could redirect to the new page, but again that's up to the pgfoundry overlords.

**Comment by petere** [comment]
Put the project description on GitHub still shows the old home page, which you can edit.

**Comment by dvarrazzo** [comment]
Links updated
